/**
 * @authors: Vinay Maruri, Terry Drinkwater
 * @Version: 1.0
 * A class for starting a new game, and printing out
 * the world generated by the seed.
 */
package byog.Core;

import byog.TileEngine.TETile;

public class Seed {
    public static void main(String[] args) {
        Game game = new Game(12345);
        TETile[][] world = game.playWithInputString("n123s");
        System.out.println(TETile.toString(world));
    }
}
